import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import './main.css';
import './utility.css';
import Script from 'next/script';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Admin',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${inter.className} bg-body-tertiary`}>{children}</body>
      <Script type='text/javascript' src='/assets/js/main.js' />
      <Script type='text/javascript' src='/assets/js/switcher.js' />
    </html>
  );
}
